### ISSUE TITLE
Feature request: left/right and up/down transitions

### ISSUE THREAD

**Issue by jeroencoumans** [leecrossley/cordova-plugin-native-transitions#1]
Love the plugin! My humble feature request is to add native left/right transition (so you can recreate the parent->child navigation), as well as the up/down transition (so you can recreate modals).

**Comment by leecrossley** [comment]
Eddy has now created a version of this that has these features: https://github.com/Telerik-Verified-Plugins/NativePageTransitions
I plan to enhance this plugin but I suggest you use his / Telerik's for now, if it's suitable for your scenario.
