### ISSUE TITLE
Transparent curl down

### ISSUE THREAD

**Issue by james-peel** [leecrossley/cordova-plugin-native-transitions#7]
Hi - I've just set up these awesome transitions in my PhoneGap project.

I'm using curl up/curl down on the home screen to transition to/from the next page.

The curl up is working great, but the curl down, after a couple of transitions, isn't masking the content, it's transparent, but with the grey curled corner.

It's quite random, but very frequent, and it only appears to occur on the curl down effect.

Is there anything that might cause this? It's difficult to capture an image of it, and there doesn't appear to be a repetitive pattern to the occurances.

Appreciate your input.

**Comment by leecrossley** [comment]
Did you manage to resolve or work around this? It sounds like a timing issue in the js call, closing for now.
