### ISSUE TITLE
plugins.cordova.io will be deprecated in the near future

### ISSUE THREAD

**Issue by bau720123** [leecrossley/cordova-plugin-native-transitions#8]
according to this
http://phonegap.com/blog/2015/05/26/npm-plugins-available/
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

so...just want to inform you that your plugin should be move to npm in the future...

**Comment by leecrossley** [comment]
It's already been migrated, see [here](https://www.npmjs.com/package/cordova-plugin-native-transitions).

If you use Cordova CLI >= 5 you can install via:

    cordova plugin add cordova-plugin-native-transitions

and it will pull the latest code from npm.

**Comment by leecrossley** [comment]
@bau720123 please stop creating issues on various plugin Github repositories. These repositories will continue to exist for source control etc.

**Comment by bau720123** [comment]
sorry for @leecrossley 
got it
really sorry...
